
org: ssebastianaugusto
service: foodiary-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs22.x
  architecture: arm64

package:
  individually: true

build:
  esbuild:
    minify: true
    sourcemap: false

functions:
  signin:
    handler: src/function/signin.handler
    events:
      - httpApi:
          path: /signin
          method: POST
  
  signup:
    handler: src/function/signup.handler
    events:
      - httpApi:
          path: /signup
          method: POST
  
